<?php
/**
 * ConfigureCrmSyncRequestConfigurationPolicy
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Reacon\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Reacon\Sdk\Model;

use \ArrayAccess;
use \Reacon\Sdk\ObjectSerializer;

/**
 * ConfigureCrmSyncRequestConfigurationPolicy Class Doc Comment
 *
 * @category Class
 * @package  Reacon\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ConfigureCrmSyncRequestConfigurationPolicy implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'ConfigureCrmSyncRequest_configuration_policy';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'create_on' => 'string[]',
        'delete_on_lead_deleted' => 'bool',
        'log_activity' => 'bool',
        'update_on_lead_updated' => 'bool'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'create_on' => null,
        'delete_on_lead_deleted' => null,
        'log_activity' => null,
        'update_on_lead_updated' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'create_on' => false,
        'delete_on_lead_deleted' => false,
        'log_activity' => false,
        'update_on_lead_updated' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'create_on' => 'createOn',
        'delete_on_lead_deleted' => 'deleteOnLeadDeleted',
        'log_activity' => 'logActivity',
        'update_on_lead_updated' => 'updateOnLeadUpdated'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'create_on' => 'setCreateOn',
        'delete_on_lead_deleted' => 'setDeleteOnLeadDeleted',
        'log_activity' => 'setLogActivity',
        'update_on_lead_updated' => 'setUpdateOnLeadUpdated'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'create_on' => 'getCreateOn',
        'delete_on_lead_deleted' => 'getDeleteOnLeadDeleted',
        'log_activity' => 'getLogActivity',
        'update_on_lead_updated' => 'getUpdateOnLeadUpdated'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const CREATE_ON_LEAD_CREATED = 'lead.created';
    public const CREATE_ON_SEQUENCE_EMAIL_SENT = 'sequence.email.sent';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getCreateOnAllowableValues()
    {
        return [
            self::CREATE_ON_LEAD_CREATED,
            self::CREATE_ON_SEQUENCE_EMAIL_SENT,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('create_on', $data ?? [], null);
        $this->setIfExists('delete_on_lead_deleted', $data ?? [], null);
        $this->setIfExists('log_activity', $data ?? [], null);
        $this->setIfExists('update_on_lead_updated', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['create_on'] === null) {
            $invalidProperties[] = "'create_on' can't be null";
        }
        if ((count($this->container['create_on']) > 2)) {
            $invalidProperties[] = "invalid value for 'create_on', number of items must be less than or equal to 2.";
        }

        if ($this->container['delete_on_lead_deleted'] === null) {
            $invalidProperties[] = "'delete_on_lead_deleted' can't be null";
        }
        if ($this->container['log_activity'] === null) {
            $invalidProperties[] = "'log_activity' can't be null";
        }
        if ($this->container['update_on_lead_updated'] === null) {
            $invalidProperties[] = "'update_on_lead_updated' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets create_on
     *
     * @return string[]
     */
    public function getCreateOn()
    {
        return $this->container['create_on'];
    }

    /**
     * Sets create_on
     *
     * @param string[] $create_on create_on
     *
     * @return self
     */
    public function setCreateOn($create_on)
    {
        if (is_null($create_on)) {
            throw new \InvalidArgumentException('non-nullable create_on cannot be null');
        }
        $allowedValues = $this->getCreateOnAllowableValues();
        if (array_diff($create_on, $allowedValues)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'create_on', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        if ((count($create_on) > 2)) {
            throw new \InvalidArgumentException('invalid value for $create_on when calling ConfigureCrmSyncRequestConfigurationPolicy., number of items must be less than or equal to 2.');
        }
        $this->container['create_on'] = $create_on;

        return $this;
    }

    /**
     * Gets delete_on_lead_deleted
     *
     * @return bool
     */
    public function getDeleteOnLeadDeleted()
    {
        return $this->container['delete_on_lead_deleted'];
    }

    /**
     * Sets delete_on_lead_deleted
     *
     * @param bool $delete_on_lead_deleted delete_on_lead_deleted
     *
     * @return self
     */
    public function setDeleteOnLeadDeleted($delete_on_lead_deleted)
    {
        if (is_null($delete_on_lead_deleted)) {
            throw new \InvalidArgumentException('non-nullable delete_on_lead_deleted cannot be null');
        }
        $this->container['delete_on_lead_deleted'] = $delete_on_lead_deleted;

        return $this;
    }

    /**
     * Gets log_activity
     *
     * @return bool
     */
    public function getLogActivity()
    {
        return $this->container['log_activity'];
    }

    /**
     * Sets log_activity
     *
     * @param bool $log_activity log_activity
     *
     * @return self
     */
    public function setLogActivity($log_activity)
    {
        if (is_null($log_activity)) {
            throw new \InvalidArgumentException('non-nullable log_activity cannot be null');
        }
        $this->container['log_activity'] = $log_activity;

        return $this;
    }

    /**
     * Gets update_on_lead_updated
     *
     * @return bool
     */
    public function getUpdateOnLeadUpdated()
    {
        return $this->container['update_on_lead_updated'];
    }

    /**
     * Sets update_on_lead_updated
     *
     * @param bool $update_on_lead_updated update_on_lead_updated
     *
     * @return self
     */
    public function setUpdateOnLeadUpdated($update_on_lead_updated)
    {
        if (is_null($update_on_lead_updated)) {
            throw new \InvalidArgumentException('non-nullable update_on_lead_updated cannot be null');
        }
        $this->container['update_on_lead_updated'] = $update_on_lead_updated;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


