<?php
/**
 * InspectExcelWorkbookRequest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Reacon\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Reacon\Sdk\Model;

use \ArrayAccess;
use \Reacon\Sdk\ObjectSerializer;

/**
 * InspectExcelWorkbookRequest Class Doc Comment
 *
 * @category Class
 * @package  Reacon\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class InspectExcelWorkbookRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'InspectExcelWorkbookRequest';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'connection_id' => 'string',
        'drive_item_id' => 'string',
        'share_url' => 'string',
        'worksheet' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'connection_id' => null,
        'drive_item_id' => null,
        'share_url' => null,
        'worksheet' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'connection_id' => false,
        'drive_item_id' => false,
        'share_url' => false,
        'worksheet' => true
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'connection_id' => 'connectionId',
        'drive_item_id' => 'driveItemId',
        'share_url' => 'shareUrl',
        'worksheet' => 'worksheet'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'connection_id' => 'setConnectionId',
        'drive_item_id' => 'setDriveItemId',
        'share_url' => 'setShareUrl',
        'worksheet' => 'setWorksheet'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'connection_id' => 'getConnectionId',
        'drive_item_id' => 'getDriveItemId',
        'share_url' => 'getShareUrl',
        'worksheet' => 'getWorksheet'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('connection_id', $data ?? [], null);
        $this->setIfExists('drive_item_id', $data ?? [], null);
        $this->setIfExists('share_url', $data ?? [], null);
        $this->setIfExists('worksheet', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['connection_id'] === null) {
            $invalidProperties[] = "'connection_id' can't be null";
        }
        if ((mb_strlen($this->container['connection_id']) > 100)) {
            $invalidProperties[] = "invalid value for 'connection_id', the character length must be smaller than or equal to 100.";
        }

        if ((mb_strlen($this->container['connection_id']) < 1)) {
            $invalidProperties[] = "invalid value for 'connection_id', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['drive_item_id']) && (mb_strlen($this->container['drive_item_id']) > 200)) {
            $invalidProperties[] = "invalid value for 'drive_item_id', the character length must be smaller than or equal to 200.";
        }

        if (!is_null($this->container['drive_item_id']) && (mb_strlen($this->container['drive_item_id']) < 10)) {
            $invalidProperties[] = "invalid value for 'drive_item_id', the character length must be bigger than or equal to 10.";
        }

        if (!is_null($this->container['share_url']) && (mb_strlen($this->container['share_url']) > 2048)) {
            $invalidProperties[] = "invalid value for 'share_url', the character length must be smaller than or equal to 2048.";
        }

        if (!is_null($this->container['share_url']) && (mb_strlen($this->container['share_url']) < 8)) {
            $invalidProperties[] = "invalid value for 'share_url', the character length must be bigger than or equal to 8.";
        }

        if (!is_null($this->container['worksheet']) && (mb_strlen($this->container['worksheet']) > 100)) {
            $invalidProperties[] = "invalid value for 'worksheet', the character length must be smaller than or equal to 100.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets connection_id
     *
     * @return string
     */
    public function getConnectionId()
    {
        return $this->container['connection_id'];
    }

    /**
     * Sets connection_id
     *
     * @param string $connection_id connection_id
     *
     * @return self
     */
    public function setConnectionId($connection_id)
    {
        if (is_null($connection_id)) {
            throw new \InvalidArgumentException('non-nullable connection_id cannot be null');
        }
        if ((mb_strlen($connection_id) > 100)) {
            throw new \InvalidArgumentException('invalid length for $connection_id when calling InspectExcelWorkbookRequest., must be smaller than or equal to 100.');
        }
        if ((mb_strlen($connection_id) < 1)) {
            throw new \InvalidArgumentException('invalid length for $connection_id when calling InspectExcelWorkbookRequest., must be bigger than or equal to 1.');
        }

        $this->container['connection_id'] = $connection_id;

        return $this;
    }

    /**
     * Gets drive_item_id
     *
     * @return string|null
     */
    public function getDriveItemId()
    {
        return $this->container['drive_item_id'];
    }

    /**
     * Sets drive_item_id
     *
     * @param string|null $drive_item_id drive_item_id
     *
     * @return self
     */
    public function setDriveItemId($drive_item_id)
    {
        if (is_null($drive_item_id)) {
            throw new \InvalidArgumentException('non-nullable drive_item_id cannot be null');
        }
        if ((mb_strlen($drive_item_id) > 200)) {
            throw new \InvalidArgumentException('invalid length for $drive_item_id when calling InspectExcelWorkbookRequest., must be smaller than or equal to 200.');
        }
        if ((mb_strlen($drive_item_id) < 10)) {
            throw new \InvalidArgumentException('invalid length for $drive_item_id when calling InspectExcelWorkbookRequest., must be bigger than or equal to 10.');
        }

        $this->container['drive_item_id'] = $drive_item_id;

        return $this;
    }

    /**
     * Gets share_url
     *
     * @return string|null
     */
    public function getShareUrl()
    {
        return $this->container['share_url'];
    }

    /**
     * Sets share_url
     *
     * @param string|null $share_url share_url
     *
     * @return self
     */
    public function setShareUrl($share_url)
    {
        if (is_null($share_url)) {
            throw new \InvalidArgumentException('non-nullable share_url cannot be null');
        }
        if ((mb_strlen($share_url) > 2048)) {
            throw new \InvalidArgumentException('invalid length for $share_url when calling InspectExcelWorkbookRequest., must be smaller than or equal to 2048.');
        }
        if ((mb_strlen($share_url) < 8)) {
            throw new \InvalidArgumentException('invalid length for $share_url when calling InspectExcelWorkbookRequest., must be bigger than or equal to 8.');
        }

        $this->container['share_url'] = $share_url;

        return $this;
    }

    /**
     * Gets worksheet
     *
     * @return string|null
     */
    public function getWorksheet()
    {
        return $this->container['worksheet'];
    }

    /**
     * Sets worksheet
     *
     * @param string|null $worksheet worksheet
     *
     * @return self
     */
    public function setWorksheet($worksheet)
    {
        if (is_null($worksheet)) {
            array_push($this->openAPINullablesSetToNull, 'worksheet');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('worksheet', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($worksheet) && (mb_strlen($worksheet) > 100)) {
            throw new \InvalidArgumentException('invalid length for $worksheet when calling InspectExcelWorkbookRequest., must be smaller than or equal to 100.');
        }

        $this->container['worksheet'] = $worksheet;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


