<?php
/**
 * MailExperimentReport
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Reacon\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Reacon\Sdk\Model;

use \ArrayAccess;
use \Reacon\Sdk\ObjectSerializer;

/**
 * MailExperimentReport Class Doc Comment
 *
 * @category Class
 * @package  Reacon\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class MailExperimentReport implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'MailExperimentReport';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'assigned' => 'float',
        'assignment_sample_ratio_mismatch' => 'bool',
        'automatic_decision_blockers' => 'string[]',
        'automatic_decision_eligible' => 'bool',
        'decision' => '\Reacon\Sdk\Model\MailExperimentDecisionRecord',
        'decision_blockers' => 'string[]',
        'definition' => '\Reacon\Sdk\Model\MailExperimentDefinitionRecord',
        'eligible_for_decision' => 'bool',
        'exposed' => 'float',
        'exposure_sample_ratio_mismatch' => 'bool',
        'generated_at' => '\DateTime',
        'matured' => 'float',
        'pending_maturity' => 'float',
        'recommended_winner_variant_id' => 'string',
        'revision' => '\Reacon\Sdk\Model\MailExperimentRevisionRecord',
        'variants' => '\Reacon\Sdk\Model\MailExperimentVariantReport[]'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'assigned' => null,
        'assignment_sample_ratio_mismatch' => null,
        'automatic_decision_blockers' => null,
        'automatic_decision_eligible' => null,
        'decision' => null,
        'decision_blockers' => null,
        'definition' => null,
        'eligible_for_decision' => null,
        'exposed' => null,
        'exposure_sample_ratio_mismatch' => null,
        'generated_at' => 'date-time',
        'matured' => null,
        'pending_maturity' => null,
        'recommended_winner_variant_id' => null,
        'revision' => null,
        'variants' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'assigned' => false,
        'assignment_sample_ratio_mismatch' => false,
        'automatic_decision_blockers' => false,
        'automatic_decision_eligible' => false,
        'decision' => true,
        'decision_blockers' => false,
        'definition' => false,
        'eligible_for_decision' => false,
        'exposed' => false,
        'exposure_sample_ratio_mismatch' => false,
        'generated_at' => false,
        'matured' => false,
        'pending_maturity' => false,
        'recommended_winner_variant_id' => true,
        'revision' => false,
        'variants' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'assigned' => 'assigned',
        'assignment_sample_ratio_mismatch' => 'assignmentSampleRatioMismatch',
        'automatic_decision_blockers' => 'automaticDecisionBlockers',
        'automatic_decision_eligible' => 'automaticDecisionEligible',
        'decision' => 'decision',
        'decision_blockers' => 'decisionBlockers',
        'definition' => 'definition',
        'eligible_for_decision' => 'eligibleForDecision',
        'exposed' => 'exposed',
        'exposure_sample_ratio_mismatch' => 'exposureSampleRatioMismatch',
        'generated_at' => 'generatedAt',
        'matured' => 'matured',
        'pending_maturity' => 'pendingMaturity',
        'recommended_winner_variant_id' => 'recommendedWinnerVariantId',
        'revision' => 'revision',
        'variants' => 'variants'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'assigned' => 'setAssigned',
        'assignment_sample_ratio_mismatch' => 'setAssignmentSampleRatioMismatch',
        'automatic_decision_blockers' => 'setAutomaticDecisionBlockers',
        'automatic_decision_eligible' => 'setAutomaticDecisionEligible',
        'decision' => 'setDecision',
        'decision_blockers' => 'setDecisionBlockers',
        'definition' => 'setDefinition',
        'eligible_for_decision' => 'setEligibleForDecision',
        'exposed' => 'setExposed',
        'exposure_sample_ratio_mismatch' => 'setExposureSampleRatioMismatch',
        'generated_at' => 'setGeneratedAt',
        'matured' => 'setMatured',
        'pending_maturity' => 'setPendingMaturity',
        'recommended_winner_variant_id' => 'setRecommendedWinnerVariantId',
        'revision' => 'setRevision',
        'variants' => 'setVariants'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'assigned' => 'getAssigned',
        'assignment_sample_ratio_mismatch' => 'getAssignmentSampleRatioMismatch',
        'automatic_decision_blockers' => 'getAutomaticDecisionBlockers',
        'automatic_decision_eligible' => 'getAutomaticDecisionEligible',
        'decision' => 'getDecision',
        'decision_blockers' => 'getDecisionBlockers',
        'definition' => 'getDefinition',
        'eligible_for_decision' => 'getEligibleForDecision',
        'exposed' => 'getExposed',
        'exposure_sample_ratio_mismatch' => 'getExposureSampleRatioMismatch',
        'generated_at' => 'getGeneratedAt',
        'matured' => 'getMatured',
        'pending_maturity' => 'getPendingMaturity',
        'recommended_winner_variant_id' => 'getRecommendedWinnerVariantId',
        'revision' => 'getRevision',
        'variants' => 'getVariants'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('assigned', $data ?? [], null);
        $this->setIfExists('assignment_sample_ratio_mismatch', $data ?? [], null);
        $this->setIfExists('automatic_decision_blockers', $data ?? [], null);
        $this->setIfExists('automatic_decision_eligible', $data ?? [], null);
        $this->setIfExists('decision', $data ?? [], null);
        $this->setIfExists('decision_blockers', $data ?? [], null);
        $this->setIfExists('definition', $data ?? [], null);
        $this->setIfExists('eligible_for_decision', $data ?? [], null);
        $this->setIfExists('exposed', $data ?? [], null);
        $this->setIfExists('exposure_sample_ratio_mismatch', $data ?? [], null);
        $this->setIfExists('generated_at', $data ?? [], null);
        $this->setIfExists('matured', $data ?? [], null);
        $this->setIfExists('pending_maturity', $data ?? [], null);
        $this->setIfExists('recommended_winner_variant_id', $data ?? [], null);
        $this->setIfExists('revision', $data ?? [], null);
        $this->setIfExists('variants', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['assigned'] === null) {
            $invalidProperties[] = "'assigned' can't be null";
        }
        if ($this->container['assignment_sample_ratio_mismatch'] === null) {
            $invalidProperties[] = "'assignment_sample_ratio_mismatch' can't be null";
        }
        if ($this->container['automatic_decision_blockers'] === null) {
            $invalidProperties[] = "'automatic_decision_blockers' can't be null";
        }
        if ($this->container['automatic_decision_eligible'] === null) {
            $invalidProperties[] = "'automatic_decision_eligible' can't be null";
        }
        if ($this->container['decision'] === null && !$this->isNullableSetToNull('decision')) {
            $invalidProperties[] = "'decision' can't be null";
        }
        if ($this->container['decision_blockers'] === null) {
            $invalidProperties[] = "'decision_blockers' can't be null";
        }
        if ($this->container['definition'] === null) {
            $invalidProperties[] = "'definition' can't be null";
        }
        if ($this->container['eligible_for_decision'] === null) {
            $invalidProperties[] = "'eligible_for_decision' can't be null";
        }
        if ($this->container['exposed'] === null) {
            $invalidProperties[] = "'exposed' can't be null";
        }
        if ($this->container['exposure_sample_ratio_mismatch'] === null) {
            $invalidProperties[] = "'exposure_sample_ratio_mismatch' can't be null";
        }
        if ($this->container['generated_at'] === null) {
            $invalidProperties[] = "'generated_at' can't be null";
        }
        if ($this->container['matured'] === null) {
            $invalidProperties[] = "'matured' can't be null";
        }
        if ($this->container['pending_maturity'] === null) {
            $invalidProperties[] = "'pending_maturity' can't be null";
        }
        if ($this->container['recommended_winner_variant_id'] === null && !$this->isNullableSetToNull('recommended_winner_variant_id')) {
            $invalidProperties[] = "'recommended_winner_variant_id' is required";
        }
        if ($this->container['revision'] === null) {
            $invalidProperties[] = "'revision' can't be null";
        }
        if ($this->container['variants'] === null) {
            $invalidProperties[] = "'variants' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets assigned
     *
     * @return float
     */
    public function getAssigned()
    {
        return $this->container['assigned'];
    }

    /**
     * Sets assigned
     *
     * @param float $assigned assigned
     *
     * @return self
     */
    public function setAssigned($assigned)
    {
        if (is_null($assigned)) {
            throw new \InvalidArgumentException('non-nullable assigned cannot be null');
        }
        $this->container['assigned'] = $assigned;

        return $this;
    }

    /**
     * Gets assignment_sample_ratio_mismatch
     *
     * @return bool
     */
    public function getAssignmentSampleRatioMismatch()
    {
        return $this->container['assignment_sample_ratio_mismatch'];
    }

    /**
     * Sets assignment_sample_ratio_mismatch
     *
     * @param bool $assignment_sample_ratio_mismatch assignment_sample_ratio_mismatch
     *
     * @return self
     */
    public function setAssignmentSampleRatioMismatch($assignment_sample_ratio_mismatch)
    {
        if (is_null($assignment_sample_ratio_mismatch)) {
            throw new \InvalidArgumentException('non-nullable assignment_sample_ratio_mismatch cannot be null');
        }
        $this->container['assignment_sample_ratio_mismatch'] = $assignment_sample_ratio_mismatch;

        return $this;
    }

    /**
     * Gets automatic_decision_blockers
     *
     * @return string[]
     */
    public function getAutomaticDecisionBlockers()
    {
        return $this->container['automatic_decision_blockers'];
    }

    /**
     * Sets automatic_decision_blockers
     *
     * @param string[] $automatic_decision_blockers automatic_decision_blockers
     *
     * @return self
     */
    public function setAutomaticDecisionBlockers($automatic_decision_blockers)
    {
        if (is_null($automatic_decision_blockers)) {
            throw new \InvalidArgumentException('non-nullable automatic_decision_blockers cannot be null');
        }
        $this->container['automatic_decision_blockers'] = $automatic_decision_blockers;

        return $this;
    }

    /**
     * Gets automatic_decision_eligible
     *
     * @return bool
     */
    public function getAutomaticDecisionEligible()
    {
        return $this->container['automatic_decision_eligible'];
    }

    /**
     * Sets automatic_decision_eligible
     *
     * @param bool $automatic_decision_eligible automatic_decision_eligible
     *
     * @return self
     */
    public function setAutomaticDecisionEligible($automatic_decision_eligible)
    {
        if (is_null($automatic_decision_eligible)) {
            throw new \InvalidArgumentException('non-nullable automatic_decision_eligible cannot be null');
        }
        $this->container['automatic_decision_eligible'] = $automatic_decision_eligible;

        return $this;
    }

    /**
     * Gets decision
     *
     * @return \Reacon\Sdk\Model\MailExperimentDecisionRecord
     */
    public function getDecision()
    {
        return $this->container['decision'];
    }

    /**
     * Sets decision
     *
     * @param \Reacon\Sdk\Model\MailExperimentDecisionRecord $decision decision
     *
     * @return self
     */
    public function setDecision($decision)
    {
        $this->openAPINullablesSetToNull = array_values(array_diff($this->openAPINullablesSetToNull, ['decision']));
        if (is_null($decision)) {
            $this->openAPINullablesSetToNull[] = 'decision';
        }
        $this->container['decision'] = $decision;

        return $this;
    }

    /**
     * Gets decision_blockers
     *
     * @return string[]
     */
    public function getDecisionBlockers()
    {
        return $this->container['decision_blockers'];
    }

    /**
     * Sets decision_blockers
     *
     * @param string[] $decision_blockers decision_blockers
     *
     * @return self
     */
    public function setDecisionBlockers($decision_blockers)
    {
        if (is_null($decision_blockers)) {
            throw new \InvalidArgumentException('non-nullable decision_blockers cannot be null');
        }
        $this->container['decision_blockers'] = $decision_blockers;

        return $this;
    }

    /**
     * Gets definition
     *
     * @return \Reacon\Sdk\Model\MailExperimentDefinitionRecord
     */
    public function getDefinition()
    {
        return $this->container['definition'];
    }

    /**
     * Sets definition
     *
     * @param \Reacon\Sdk\Model\MailExperimentDefinitionRecord $definition definition
     *
     * @return self
     */
    public function setDefinition($definition)
    {
        if (is_null($definition)) {
            throw new \InvalidArgumentException('non-nullable definition cannot be null');
        }
        $this->container['definition'] = $definition;

        return $this;
    }

    /**
     * Gets eligible_for_decision
     *
     * @return bool
     */
    public function getEligibleForDecision()
    {
        return $this->container['eligible_for_decision'];
    }

    /**
     * Sets eligible_for_decision
     *
     * @param bool $eligible_for_decision eligible_for_decision
     *
     * @return self
     */
    public function setEligibleForDecision($eligible_for_decision)
    {
        if (is_null($eligible_for_decision)) {
            throw new \InvalidArgumentException('non-nullable eligible_for_decision cannot be null');
        }
        $this->container['eligible_for_decision'] = $eligible_for_decision;

        return $this;
    }

    /**
     * Gets exposed
     *
     * @return float
     */
    public function getExposed()
    {
        return $this->container['exposed'];
    }

    /**
     * Sets exposed
     *
     * @param float $exposed exposed
     *
     * @return self
     */
    public function setExposed($exposed)
    {
        if (is_null($exposed)) {
            throw new \InvalidArgumentException('non-nullable exposed cannot be null');
        }
        $this->container['exposed'] = $exposed;

        return $this;
    }

    /**
     * Gets exposure_sample_ratio_mismatch
     *
     * @return bool
     */
    public function getExposureSampleRatioMismatch()
    {
        return $this->container['exposure_sample_ratio_mismatch'];
    }

    /**
     * Sets exposure_sample_ratio_mismatch
     *
     * @param bool $exposure_sample_ratio_mismatch exposure_sample_ratio_mismatch
     *
     * @return self
     */
    public function setExposureSampleRatioMismatch($exposure_sample_ratio_mismatch)
    {
        if (is_null($exposure_sample_ratio_mismatch)) {
            throw new \InvalidArgumentException('non-nullable exposure_sample_ratio_mismatch cannot be null');
        }
        $this->container['exposure_sample_ratio_mismatch'] = $exposure_sample_ratio_mismatch;

        return $this;
    }

    /**
     * Gets generated_at
     *
     * @return \DateTime
     */
    public function getGeneratedAt()
    {
        return $this->container['generated_at'];
    }

    /**
     * Sets generated_at
     *
     * @param \DateTime $generated_at generated_at
     *
     * @return self
     */
    public function setGeneratedAt($generated_at)
    {
        if (is_null($generated_at)) {
            throw new \InvalidArgumentException('non-nullable generated_at cannot be null');
        }
        $this->container['generated_at'] = $generated_at;

        return $this;
    }

    /**
     * Gets matured
     *
     * @return float
     */
    public function getMatured()
    {
        return $this->container['matured'];
    }

    /**
     * Sets matured
     *
     * @param float $matured matured
     *
     * @return self
     */
    public function setMatured($matured)
    {
        if (is_null($matured)) {
            throw new \InvalidArgumentException('non-nullable matured cannot be null');
        }
        $this->container['matured'] = $matured;

        return $this;
    }

    /**
     * Gets pending_maturity
     *
     * @return float
     */
    public function getPendingMaturity()
    {
        return $this->container['pending_maturity'];
    }

    /**
     * Sets pending_maturity
     *
     * @param float $pending_maturity pending_maturity
     *
     * @return self
     */
    public function setPendingMaturity($pending_maturity)
    {
        if (is_null($pending_maturity)) {
            throw new \InvalidArgumentException('non-nullable pending_maturity cannot be null');
        }
        $this->container['pending_maturity'] = $pending_maturity;

        return $this;
    }

    /**
     * Gets recommended_winner_variant_id
     *
     * @return string|null
     */
    public function getRecommendedWinnerVariantId()
    {
        return $this->container['recommended_winner_variant_id'];
    }

    /**
     * Sets recommended_winner_variant_id
     *
     * @param string|null $recommended_winner_variant_id recommended_winner_variant_id
     *
     * @return self
     */
    public function setRecommendedWinnerVariantId($recommended_winner_variant_id)
    {
        if (is_null($recommended_winner_variant_id)) {
            array_push($this->openAPINullablesSetToNull, 'recommended_winner_variant_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('recommended_winner_variant_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['recommended_winner_variant_id'] = $recommended_winner_variant_id;

        return $this;
    }

    /**
     * Gets revision
     *
     * @return \Reacon\Sdk\Model\MailExperimentRevisionRecord
     */
    public function getRevision()
    {
        return $this->container['revision'];
    }

    /**
     * Sets revision
     *
     * @param \Reacon\Sdk\Model\MailExperimentRevisionRecord $revision revision
     *
     * @return self
     */
    public function setRevision($revision)
    {
        if (is_null($revision)) {
            throw new \InvalidArgumentException('non-nullable revision cannot be null');
        }
        $this->container['revision'] = $revision;

        return $this;
    }

    /**
     * Gets variants
     *
     * @return \Reacon\Sdk\Model\MailExperimentVariantReport[]
     */
    public function getVariants()
    {
        return $this->container['variants'];
    }

    /**
     * Sets variants
     *
     * @param \Reacon\Sdk\Model\MailExperimentVariantReport[] $variants variants
     *
     * @return self
     */
    public function setVariants($variants)
    {
        if (is_null($variants)) {
            throw new \InvalidArgumentException('non-nullable variants cannot be null');
        }
        $this->container['variants'] = $variants;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


