<?php
/**
 * MailMessagePolicyInput
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Reacon\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Reacon\Sdk\Model;

use \ArrayAccess;
use \Reacon\Sdk\ObjectSerializer;

/**
 * MailMessagePolicyInput Class Doc Comment
 *
 * @category Class
 * @package  Reacon\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class MailMessagePolicyInput implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'MailMessagePolicyInput';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'domain_quotas' => '\Reacon\Sdk\Model\MailQuotaRule[]',
        'mailbox_quotas' => '\Reacon\Sdk\Model\MailQuotaRule[]',
        'recipient_cooldown_ms' => 'float',
        'recipient_quotas' => '\Reacon\Sdk\Model\MailQuotaRule[]',
        'sending_windows' => '\Reacon\Sdk\Model\MailSendingWindow[]',
        'tenant_quotas' => '\Reacon\Sdk\Model\MailQuotaRule[]',
        'time_zone' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'domain_quotas' => null,
        'mailbox_quotas' => null,
        'recipient_cooldown_ms' => null,
        'recipient_quotas' => null,
        'sending_windows' => null,
        'tenant_quotas' => null,
        'time_zone' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'domain_quotas' => false,
        'mailbox_quotas' => false,
        'recipient_cooldown_ms' => false,
        'recipient_quotas' => false,
        'sending_windows' => false,
        'tenant_quotas' => false,
        'time_zone' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'domain_quotas' => 'domainQuotas',
        'mailbox_quotas' => 'mailboxQuotas',
        'recipient_cooldown_ms' => 'recipientCooldownMs',
        'recipient_quotas' => 'recipientQuotas',
        'sending_windows' => 'sendingWindows',
        'tenant_quotas' => 'tenantQuotas',
        'time_zone' => 'timeZone'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'domain_quotas' => 'setDomainQuotas',
        'mailbox_quotas' => 'setMailboxQuotas',
        'recipient_cooldown_ms' => 'setRecipientCooldownMs',
        'recipient_quotas' => 'setRecipientQuotas',
        'sending_windows' => 'setSendingWindows',
        'tenant_quotas' => 'setTenantQuotas',
        'time_zone' => 'setTimeZone'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'domain_quotas' => 'getDomainQuotas',
        'mailbox_quotas' => 'getMailboxQuotas',
        'recipient_cooldown_ms' => 'getRecipientCooldownMs',
        'recipient_quotas' => 'getRecipientQuotas',
        'sending_windows' => 'getSendingWindows',
        'tenant_quotas' => 'getTenantQuotas',
        'time_zone' => 'getTimeZone'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('domain_quotas', $data ?? [], null);
        $this->setIfExists('mailbox_quotas', $data ?? [], null);
        $this->setIfExists('recipient_cooldown_ms', $data ?? [], null);
        $this->setIfExists('recipient_quotas', $data ?? [], null);
        $this->setIfExists('sending_windows', $data ?? [], null);
        $this->setIfExists('tenant_quotas', $data ?? [], null);
        $this->setIfExists('time_zone', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets domain_quotas
     *
     * @return \Reacon\Sdk\Model\MailQuotaRule[]|null
     */
    public function getDomainQuotas()
    {
        return $this->container['domain_quotas'];
    }

    /**
     * Sets domain_quotas
     *
     * @param \Reacon\Sdk\Model\MailQuotaRule[]|null $domain_quotas domain_quotas
     *
     * @return self
     */
    public function setDomainQuotas($domain_quotas)
    {
        if (is_null($domain_quotas)) {
            throw new \InvalidArgumentException('non-nullable domain_quotas cannot be null');
        }
        $this->container['domain_quotas'] = $domain_quotas;

        return $this;
    }

    /**
     * Gets mailbox_quotas
     *
     * @return \Reacon\Sdk\Model\MailQuotaRule[]|null
     */
    public function getMailboxQuotas()
    {
        return $this->container['mailbox_quotas'];
    }

    /**
     * Sets mailbox_quotas
     *
     * @param \Reacon\Sdk\Model\MailQuotaRule[]|null $mailbox_quotas mailbox_quotas
     *
     * @return self
     */
    public function setMailboxQuotas($mailbox_quotas)
    {
        if (is_null($mailbox_quotas)) {
            throw new \InvalidArgumentException('non-nullable mailbox_quotas cannot be null');
        }
        $this->container['mailbox_quotas'] = $mailbox_quotas;

        return $this;
    }

    /**
     * Gets recipient_cooldown_ms
     *
     * @return float|null
     */
    public function getRecipientCooldownMs()
    {
        return $this->container['recipient_cooldown_ms'];
    }

    /**
     * Sets recipient_cooldown_ms
     *
     * @param float|null $recipient_cooldown_ms recipient_cooldown_ms
     *
     * @return self
     */
    public function setRecipientCooldownMs($recipient_cooldown_ms)
    {
        if (is_null($recipient_cooldown_ms)) {
            throw new \InvalidArgumentException('non-nullable recipient_cooldown_ms cannot be null');
        }
        $this->container['recipient_cooldown_ms'] = $recipient_cooldown_ms;

        return $this;
    }

    /**
     * Gets recipient_quotas
     *
     * @return \Reacon\Sdk\Model\MailQuotaRule[]|null
     */
    public function getRecipientQuotas()
    {
        return $this->container['recipient_quotas'];
    }

    /**
     * Sets recipient_quotas
     *
     * @param \Reacon\Sdk\Model\MailQuotaRule[]|null $recipient_quotas recipient_quotas
     *
     * @return self
     */
    public function setRecipientQuotas($recipient_quotas)
    {
        if (is_null($recipient_quotas)) {
            throw new \InvalidArgumentException('non-nullable recipient_quotas cannot be null');
        }
        $this->container['recipient_quotas'] = $recipient_quotas;

        return $this;
    }

    /**
     * Gets sending_windows
     *
     * @return \Reacon\Sdk\Model\MailSendingWindow[]|null
     */
    public function getSendingWindows()
    {
        return $this->container['sending_windows'];
    }

    /**
     * Sets sending_windows
     *
     * @param \Reacon\Sdk\Model\MailSendingWindow[]|null $sending_windows sending_windows
     *
     * @return self
     */
    public function setSendingWindows($sending_windows)
    {
        if (is_null($sending_windows)) {
            throw new \InvalidArgumentException('non-nullable sending_windows cannot be null');
        }
        $this->container['sending_windows'] = $sending_windows;

        return $this;
    }

    /**
     * Gets tenant_quotas
     *
     * @return \Reacon\Sdk\Model\MailQuotaRule[]|null
     */
    public function getTenantQuotas()
    {
        return $this->container['tenant_quotas'];
    }

    /**
     * Sets tenant_quotas
     *
     * @param \Reacon\Sdk\Model\MailQuotaRule[]|null $tenant_quotas tenant_quotas
     *
     * @return self
     */
    public function setTenantQuotas($tenant_quotas)
    {
        if (is_null($tenant_quotas)) {
            throw new \InvalidArgumentException('non-nullable tenant_quotas cannot be null');
        }
        $this->container['tenant_quotas'] = $tenant_quotas;

        return $this;
    }

    /**
     * Gets time_zone
     *
     * @return string|null
     */
    public function getTimeZone()
    {
        return $this->container['time_zone'];
    }

    /**
     * Sets time_zone
     *
     * @param string|null $time_zone time_zone
     *
     * @return self
     */
    public function setTimeZone($time_zone)
    {
        if (is_null($time_zone)) {
            throw new \InvalidArgumentException('non-nullable time_zone cannot be null');
        }
        $this->container['time_zone'] = $time_zone;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


