<?php
/**
 * MailCampaignProgressMessageCounts
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Reacon\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Reacon\Sdk\Model;

use \ArrayAccess;
use \Reacon\Sdk\ObjectSerializer;

/**
 * MailCampaignProgressMessageCounts Class Doc Comment
 *
 * @category Class
 * @package  Reacon\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class MailCampaignProgressMessageCounts implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'MailCampaignProgress_messageCounts';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'auto_replied' => 'float',
        'bounced' => 'float',
        'cancelled' => 'float',
        'complained' => 'float',
        'delivered' => 'float',
        'failed' => 'float',
        'provider_accepted' => 'float',
        'queued' => 'float',
        'replied' => 'float',
        'retry_scheduled' => 'float',
        'sending' => 'float',
        'suppressed' => 'float',
        'unsubscribed' => 'float'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'auto_replied' => null,
        'bounced' => null,
        'cancelled' => null,
        'complained' => null,
        'delivered' => null,
        'failed' => null,
        'provider_accepted' => null,
        'queued' => null,
        'replied' => null,
        'retry_scheduled' => null,
        'sending' => null,
        'suppressed' => null,
        'unsubscribed' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'auto_replied' => false,
        'bounced' => false,
        'cancelled' => false,
        'complained' => false,
        'delivered' => false,
        'failed' => false,
        'provider_accepted' => false,
        'queued' => false,
        'replied' => false,
        'retry_scheduled' => false,
        'sending' => false,
        'suppressed' => false,
        'unsubscribed' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'auto_replied' => 'auto_replied',
        'bounced' => 'bounced',
        'cancelled' => 'cancelled',
        'complained' => 'complained',
        'delivered' => 'delivered',
        'failed' => 'failed',
        'provider_accepted' => 'provider_accepted',
        'queued' => 'queued',
        'replied' => 'replied',
        'retry_scheduled' => 'retry_scheduled',
        'sending' => 'sending',
        'suppressed' => 'suppressed',
        'unsubscribed' => 'unsubscribed'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'auto_replied' => 'setAutoReplied',
        'bounced' => 'setBounced',
        'cancelled' => 'setCancelled',
        'complained' => 'setComplained',
        'delivered' => 'setDelivered',
        'failed' => 'setFailed',
        'provider_accepted' => 'setProviderAccepted',
        'queued' => 'setQueued',
        'replied' => 'setReplied',
        'retry_scheduled' => 'setRetryScheduled',
        'sending' => 'setSending',
        'suppressed' => 'setSuppressed',
        'unsubscribed' => 'setUnsubscribed'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'auto_replied' => 'getAutoReplied',
        'bounced' => 'getBounced',
        'cancelled' => 'getCancelled',
        'complained' => 'getComplained',
        'delivered' => 'getDelivered',
        'failed' => 'getFailed',
        'provider_accepted' => 'getProviderAccepted',
        'queued' => 'getQueued',
        'replied' => 'getReplied',
        'retry_scheduled' => 'getRetryScheduled',
        'sending' => 'getSending',
        'suppressed' => 'getSuppressed',
        'unsubscribed' => 'getUnsubscribed'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('auto_replied', $data ?? [], null);
        $this->setIfExists('bounced', $data ?? [], null);
        $this->setIfExists('cancelled', $data ?? [], null);
        $this->setIfExists('complained', $data ?? [], null);
        $this->setIfExists('delivered', $data ?? [], null);
        $this->setIfExists('failed', $data ?? [], null);
        $this->setIfExists('provider_accepted', $data ?? [], null);
        $this->setIfExists('queued', $data ?? [], null);
        $this->setIfExists('replied', $data ?? [], null);
        $this->setIfExists('retry_scheduled', $data ?? [], null);
        $this->setIfExists('sending', $data ?? [], null);
        $this->setIfExists('suppressed', $data ?? [], null);
        $this->setIfExists('unsubscribed', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets auto_replied
     *
     * @return float|null
     */
    public function getAutoReplied()
    {
        return $this->container['auto_replied'];
    }

    /**
     * Sets auto_replied
     *
     * @param float|null $auto_replied auto_replied
     *
     * @return self
     */
    public function setAutoReplied($auto_replied)
    {
        if (is_null($auto_replied)) {
            throw new \InvalidArgumentException('non-nullable auto_replied cannot be null');
        }
        $this->container['auto_replied'] = $auto_replied;

        return $this;
    }

    /**
     * Gets bounced
     *
     * @return float|null
     */
    public function getBounced()
    {
        return $this->container['bounced'];
    }

    /**
     * Sets bounced
     *
     * @param float|null $bounced bounced
     *
     * @return self
     */
    public function setBounced($bounced)
    {
        if (is_null($bounced)) {
            throw new \InvalidArgumentException('non-nullable bounced cannot be null');
        }
        $this->container['bounced'] = $bounced;

        return $this;
    }

    /**
     * Gets cancelled
     *
     * @return float|null
     */
    public function getCancelled()
    {
        return $this->container['cancelled'];
    }

    /**
     * Sets cancelled
     *
     * @param float|null $cancelled cancelled
     *
     * @return self
     */
    public function setCancelled($cancelled)
    {
        if (is_null($cancelled)) {
            throw new \InvalidArgumentException('non-nullable cancelled cannot be null');
        }
        $this->container['cancelled'] = $cancelled;

        return $this;
    }

    /**
     * Gets complained
     *
     * @return float|null
     */
    public function getComplained()
    {
        return $this->container['complained'];
    }

    /**
     * Sets complained
     *
     * @param float|null $complained complained
     *
     * @return self
     */
    public function setComplained($complained)
    {
        if (is_null($complained)) {
            throw new \InvalidArgumentException('non-nullable complained cannot be null');
        }
        $this->container['complained'] = $complained;

        return $this;
    }

    /**
     * Gets delivered
     *
     * @return float|null
     */
    public function getDelivered()
    {
        return $this->container['delivered'];
    }

    /**
     * Sets delivered
     *
     * @param float|null $delivered delivered
     *
     * @return self
     */
    public function setDelivered($delivered)
    {
        if (is_null($delivered)) {
            throw new \InvalidArgumentException('non-nullable delivered cannot be null');
        }
        $this->container['delivered'] = $delivered;

        return $this;
    }

    /**
     * Gets failed
     *
     * @return float|null
     */
    public function getFailed()
    {
        return $this->container['failed'];
    }

    /**
     * Sets failed
     *
     * @param float|null $failed failed
     *
     * @return self
     */
    public function setFailed($failed)
    {
        if (is_null($failed)) {
            throw new \InvalidArgumentException('non-nullable failed cannot be null');
        }
        $this->container['failed'] = $failed;

        return $this;
    }

    /**
     * Gets provider_accepted
     *
     * @return float|null
     */
    public function getProviderAccepted()
    {
        return $this->container['provider_accepted'];
    }

    /**
     * Sets provider_accepted
     *
     * @param float|null $provider_accepted provider_accepted
     *
     * @return self
     */
    public function setProviderAccepted($provider_accepted)
    {
        if (is_null($provider_accepted)) {
            throw new \InvalidArgumentException('non-nullable provider_accepted cannot be null');
        }
        $this->container['provider_accepted'] = $provider_accepted;

        return $this;
    }

    /**
     * Gets queued
     *
     * @return float|null
     */
    public function getQueued()
    {
        return $this->container['queued'];
    }

    /**
     * Sets queued
     *
     * @param float|null $queued queued
     *
     * @return self
     */
    public function setQueued($queued)
    {
        if (is_null($queued)) {
            throw new \InvalidArgumentException('non-nullable queued cannot be null');
        }
        $this->container['queued'] = $queued;

        return $this;
    }

    /**
     * Gets replied
     *
     * @return float|null
     */
    public function getReplied()
    {
        return $this->container['replied'];
    }

    /**
     * Sets replied
     *
     * @param float|null $replied replied
     *
     * @return self
     */
    public function setReplied($replied)
    {
        if (is_null($replied)) {
            throw new \InvalidArgumentException('non-nullable replied cannot be null');
        }
        $this->container['replied'] = $replied;

        return $this;
    }

    /**
     * Gets retry_scheduled
     *
     * @return float|null
     */
    public function getRetryScheduled()
    {
        return $this->container['retry_scheduled'];
    }

    /**
     * Sets retry_scheduled
     *
     * @param float|null $retry_scheduled retry_scheduled
     *
     * @return self
     */
    public function setRetryScheduled($retry_scheduled)
    {
        if (is_null($retry_scheduled)) {
            throw new \InvalidArgumentException('non-nullable retry_scheduled cannot be null');
        }
        $this->container['retry_scheduled'] = $retry_scheduled;

        return $this;
    }

    /**
     * Gets sending
     *
     * @return float|null
     */
    public function getSending()
    {
        return $this->container['sending'];
    }

    /**
     * Sets sending
     *
     * @param float|null $sending sending
     *
     * @return self
     */
    public function setSending($sending)
    {
        if (is_null($sending)) {
            throw new \InvalidArgumentException('non-nullable sending cannot be null');
        }
        $this->container['sending'] = $sending;

        return $this;
    }

    /**
     * Gets suppressed
     *
     * @return float|null
     */
    public function getSuppressed()
    {
        return $this->container['suppressed'];
    }

    /**
     * Sets suppressed
     *
     * @param float|null $suppressed suppressed
     *
     * @return self
     */
    public function setSuppressed($suppressed)
    {
        if (is_null($suppressed)) {
            throw new \InvalidArgumentException('non-nullable suppressed cannot be null');
        }
        $this->container['suppressed'] = $suppressed;

        return $this;
    }

    /**
     * Gets unsubscribed
     *
     * @return float|null
     */
    public function getUnsubscribed()
    {
        return $this->container['unsubscribed'];
    }

    /**
     * Sets unsubscribed
     *
     * @param float|null $unsubscribed unsubscribed
     *
     * @return self
     */
    public function setUnsubscribed($unsubscribed)
    {
        if (is_null($unsubscribed)) {
            throw new \InvalidArgumentException('non-nullable unsubscribed cannot be null');
        }
        $this->container['unsubscribed'] = $unsubscribed;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


