<?php
/**
 * MailGetChannelsResponse200Whatsapp
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Reacon\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Reacon\Sdk\Model;

use \ArrayAccess;
use \Reacon\Sdk\ObjectSerializer;

/**
 * MailGetChannelsResponse200Whatsapp Class Doc Comment
 *
 * @category Class
 * @package  Reacon\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class MailGetChannelsResponse200Whatsapp implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'MailGetChannelsResponse200_whatsapp';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'approved_template_required' => 'bool',
        'configured' => 'bool',
        'consent_required' => 'bool',
        'cost_ceiling_required' => 'bool',
        'execution_enabled' => 'bool',
        'sequence_supported' => 'bool'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'approved_template_required' => null,
        'configured' => null,
        'consent_required' => null,
        'cost_ceiling_required' => null,
        'execution_enabled' => null,
        'sequence_supported' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'approved_template_required' => false,
        'configured' => false,
        'consent_required' => false,
        'cost_ceiling_required' => false,
        'execution_enabled' => false,
        'sequence_supported' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'approved_template_required' => 'approvedTemplateRequired',
        'configured' => 'configured',
        'consent_required' => 'consentRequired',
        'cost_ceiling_required' => 'costCeilingRequired',
        'execution_enabled' => 'executionEnabled',
        'sequence_supported' => 'sequenceSupported'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'approved_template_required' => 'setApprovedTemplateRequired',
        'configured' => 'setConfigured',
        'consent_required' => 'setConsentRequired',
        'cost_ceiling_required' => 'setCostCeilingRequired',
        'execution_enabled' => 'setExecutionEnabled',
        'sequence_supported' => 'setSequenceSupported'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'approved_template_required' => 'getApprovedTemplateRequired',
        'configured' => 'getConfigured',
        'consent_required' => 'getConsentRequired',
        'cost_ceiling_required' => 'getCostCeilingRequired',
        'execution_enabled' => 'getExecutionEnabled',
        'sequence_supported' => 'getSequenceSupported'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('approved_template_required', $data ?? [], null);
        $this->setIfExists('configured', $data ?? [], null);
        $this->setIfExists('consent_required', $data ?? [], null);
        $this->setIfExists('cost_ceiling_required', $data ?? [], null);
        $this->setIfExists('execution_enabled', $data ?? [], null);
        $this->setIfExists('sequence_supported', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['approved_template_required'] === null) {
            $invalidProperties[] = "'approved_template_required' can't be null";
        }
        if ($this->container['configured'] === null) {
            $invalidProperties[] = "'configured' can't be null";
        }
        if ($this->container['consent_required'] === null) {
            $invalidProperties[] = "'consent_required' can't be null";
        }
        if ($this->container['cost_ceiling_required'] === null) {
            $invalidProperties[] = "'cost_ceiling_required' can't be null";
        }
        if ($this->container['execution_enabled'] === null) {
            $invalidProperties[] = "'execution_enabled' can't be null";
        }
        if ($this->container['sequence_supported'] === null) {
            $invalidProperties[] = "'sequence_supported' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets approved_template_required
     *
     * @return bool
     */
    public function getApprovedTemplateRequired()
    {
        return $this->container['approved_template_required'];
    }

    /**
     * Sets approved_template_required
     *
     * @param bool $approved_template_required approved_template_required
     *
     * @return self
     */
    public function setApprovedTemplateRequired($approved_template_required)
    {
        if (is_null($approved_template_required)) {
            throw new \InvalidArgumentException('non-nullable approved_template_required cannot be null');
        }
        $this->container['approved_template_required'] = $approved_template_required;

        return $this;
    }

    /**
     * Gets configured
     *
     * @return bool
     */
    public function getConfigured()
    {
        return $this->container['configured'];
    }

    /**
     * Sets configured
     *
     * @param bool $configured configured
     *
     * @return self
     */
    public function setConfigured($configured)
    {
        if (is_null($configured)) {
            throw new \InvalidArgumentException('non-nullable configured cannot be null');
        }
        $this->container['configured'] = $configured;

        return $this;
    }

    /**
     * Gets consent_required
     *
     * @return bool
     */
    public function getConsentRequired()
    {
        return $this->container['consent_required'];
    }

    /**
     * Sets consent_required
     *
     * @param bool $consent_required consent_required
     *
     * @return self
     */
    public function setConsentRequired($consent_required)
    {
        if (is_null($consent_required)) {
            throw new \InvalidArgumentException('non-nullable consent_required cannot be null');
        }
        $this->container['consent_required'] = $consent_required;

        return $this;
    }

    /**
     * Gets cost_ceiling_required
     *
     * @return bool
     */
    public function getCostCeilingRequired()
    {
        return $this->container['cost_ceiling_required'];
    }

    /**
     * Sets cost_ceiling_required
     *
     * @param bool $cost_ceiling_required cost_ceiling_required
     *
     * @return self
     */
    public function setCostCeilingRequired($cost_ceiling_required)
    {
        if (is_null($cost_ceiling_required)) {
            throw new \InvalidArgumentException('non-nullable cost_ceiling_required cannot be null');
        }
        $this->container['cost_ceiling_required'] = $cost_ceiling_required;

        return $this;
    }

    /**
     * Gets execution_enabled
     *
     * @return bool
     */
    public function getExecutionEnabled()
    {
        return $this->container['execution_enabled'];
    }

    /**
     * Sets execution_enabled
     *
     * @param bool $execution_enabled execution_enabled
     *
     * @return self
     */
    public function setExecutionEnabled($execution_enabled)
    {
        if (is_null($execution_enabled)) {
            throw new \InvalidArgumentException('non-nullable execution_enabled cannot be null');
        }
        $this->container['execution_enabled'] = $execution_enabled;

        return $this;
    }

    /**
     * Gets sequence_supported
     *
     * @return bool
     */
    public function getSequenceSupported()
    {
        return $this->container['sequence_supported'];
    }

    /**
     * Sets sequence_supported
     *
     * @param bool $sequence_supported sequence_supported
     *
     * @return self
     */
    public function setSequenceSupported($sequence_supported)
    {
        if (is_null($sequence_supported)) {
            throw new \InvalidArgumentException('non-nullable sequence_supported cannot be null');
        }
        $this->container['sequence_supported'] = $sequence_supported;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


