<?php
/**
 * MailPostDeliverabilityMailboxesByMailboxIdRequest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Reacon\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Reacon\Sdk\Model;

use \ArrayAccess;
use \Reacon\Sdk\ObjectSerializer;

/**
 * MailPostDeliverabilityMailboxesByMailboxIdRequest Class Doc Comment
 *
 * @category Class
 * @description Additional server validation applies; this structural schema does not express every contextual or cross-field rule.
 * @package  Reacon\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class MailPostDeliverabilityMailboxesByMailboxIdRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'MailPostDeliverabilityMailboxesByMailboxIdRequest';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'ramp_enabled' => 'bool',
        'ramp_interval_hours' => 'int',
        'ramp_step' => 'int',
        'starting_daily_limit' => 'int',
        'target_daily_limit' => 'int'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'ramp_enabled' => null,
        'ramp_interval_hours' => null,
        'ramp_step' => null,
        'starting_daily_limit' => null,
        'target_daily_limit' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'ramp_enabled' => false,
        'ramp_interval_hours' => false,
        'ramp_step' => false,
        'starting_daily_limit' => false,
        'target_daily_limit' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'ramp_enabled' => 'rampEnabled',
        'ramp_interval_hours' => 'rampIntervalHours',
        'ramp_step' => 'rampStep',
        'starting_daily_limit' => 'startingDailyLimit',
        'target_daily_limit' => 'targetDailyLimit'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'ramp_enabled' => 'setRampEnabled',
        'ramp_interval_hours' => 'setRampIntervalHours',
        'ramp_step' => 'setRampStep',
        'starting_daily_limit' => 'setStartingDailyLimit',
        'target_daily_limit' => 'setTargetDailyLimit'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'ramp_enabled' => 'getRampEnabled',
        'ramp_interval_hours' => 'getRampIntervalHours',
        'ramp_step' => 'getRampStep',
        'starting_daily_limit' => 'getStartingDailyLimit',
        'target_daily_limit' => 'getTargetDailyLimit'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('ramp_enabled', $data ?? [], null);
        $this->setIfExists('ramp_interval_hours', $data ?? [], null);
        $this->setIfExists('ramp_step', $data ?? [], null);
        $this->setIfExists('starting_daily_limit', $data ?? [], null);
        $this->setIfExists('target_daily_limit', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['ramp_enabled'] === null) {
            $invalidProperties[] = "'ramp_enabled' can't be null";
        }
        if ($this->container['ramp_interval_hours'] === null) {
            $invalidProperties[] = "'ramp_interval_hours' can't be null";
        }
        if (($this->container['ramp_interval_hours'] > 720)) {
            $invalidProperties[] = "invalid value for 'ramp_interval_hours', must be smaller than or equal to 720.";
        }

        if (($this->container['ramp_interval_hours'] <= 0)) {
            $invalidProperties[] = "invalid value for 'ramp_interval_hours', must be bigger than 0.";
        }

        if ($this->container['ramp_step'] === null) {
            $invalidProperties[] = "'ramp_step' can't be null";
        }
        if (($this->container['ramp_step'] > 100000)) {
            $invalidProperties[] = "invalid value for 'ramp_step', must be smaller than or equal to 100000.";
        }

        if (($this->container['ramp_step'] <= 0)) {
            $invalidProperties[] = "invalid value for 'ramp_step', must be bigger than 0.";
        }

        if ($this->container['starting_daily_limit'] === null) {
            $invalidProperties[] = "'starting_daily_limit' can't be null";
        }
        if (($this->container['starting_daily_limit'] > 100000)) {
            $invalidProperties[] = "invalid value for 'starting_daily_limit', must be smaller than or equal to 100000.";
        }

        if (($this->container['starting_daily_limit'] <= 0)) {
            $invalidProperties[] = "invalid value for 'starting_daily_limit', must be bigger than 0.";
        }

        if ($this->container['target_daily_limit'] === null) {
            $invalidProperties[] = "'target_daily_limit' can't be null";
        }
        if (($this->container['target_daily_limit'] > 100000)) {
            $invalidProperties[] = "invalid value for 'target_daily_limit', must be smaller than or equal to 100000.";
        }

        if (($this->container['target_daily_limit'] <= 0)) {
            $invalidProperties[] = "invalid value for 'target_daily_limit', must be bigger than 0.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets ramp_enabled
     *
     * @return bool
     */
    public function getRampEnabled()
    {
        return $this->container['ramp_enabled'];
    }

    /**
     * Sets ramp_enabled
     *
     * @param bool $ramp_enabled ramp_enabled
     *
     * @return self
     */
    public function setRampEnabled($ramp_enabled)
    {
        if (is_null($ramp_enabled)) {
            throw new \InvalidArgumentException('non-nullable ramp_enabled cannot be null');
        }
        $this->container['ramp_enabled'] = $ramp_enabled;

        return $this;
    }

    /**
     * Gets ramp_interval_hours
     *
     * @return int
     */
    public function getRampIntervalHours()
    {
        return $this->container['ramp_interval_hours'];
    }

    /**
     * Sets ramp_interval_hours
     *
     * @param int $ramp_interval_hours ramp_interval_hours
     *
     * @return self
     */
    public function setRampIntervalHours($ramp_interval_hours)
    {
        if (is_null($ramp_interval_hours)) {
            throw new \InvalidArgumentException('non-nullable ramp_interval_hours cannot be null');
        }
        if (($ramp_interval_hours > 720)) {
            throw new \InvalidArgumentException('invalid value for $ramp_interval_hours when calling MailPostDeliverabilityMailboxesByMailboxIdRequest., must be smaller than or equal to 720.');
        }
        if (($ramp_interval_hours <= 0)) {
            throw new \InvalidArgumentException('invalid value for $ramp_interval_hours when calling MailPostDeliverabilityMailboxesByMailboxIdRequest., must be bigger than 0.');
        }

        $this->container['ramp_interval_hours'] = $ramp_interval_hours;

        return $this;
    }

    /**
     * Gets ramp_step
     *
     * @return int
     */
    public function getRampStep()
    {
        return $this->container['ramp_step'];
    }

    /**
     * Sets ramp_step
     *
     * @param int $ramp_step ramp_step
     *
     * @return self
     */
    public function setRampStep($ramp_step)
    {
        if (is_null($ramp_step)) {
            throw new \InvalidArgumentException('non-nullable ramp_step cannot be null');
        }
        if (($ramp_step > 100000)) {
            throw new \InvalidArgumentException('invalid value for $ramp_step when calling MailPostDeliverabilityMailboxesByMailboxIdRequest., must be smaller than or equal to 100000.');
        }
        if (($ramp_step <= 0)) {
            throw new \InvalidArgumentException('invalid value for $ramp_step when calling MailPostDeliverabilityMailboxesByMailboxIdRequest., must be bigger than 0.');
        }

        $this->container['ramp_step'] = $ramp_step;

        return $this;
    }

    /**
     * Gets starting_daily_limit
     *
     * @return int
     */
    public function getStartingDailyLimit()
    {
        return $this->container['starting_daily_limit'];
    }

    /**
     * Sets starting_daily_limit
     *
     * @param int $starting_daily_limit starting_daily_limit
     *
     * @return self
     */
    public function setStartingDailyLimit($starting_daily_limit)
    {
        if (is_null($starting_daily_limit)) {
            throw new \InvalidArgumentException('non-nullable starting_daily_limit cannot be null');
        }
        if (($starting_daily_limit > 100000)) {
            throw new \InvalidArgumentException('invalid value for $starting_daily_limit when calling MailPostDeliverabilityMailboxesByMailboxIdRequest., must be smaller than or equal to 100000.');
        }
        if (($starting_daily_limit <= 0)) {
            throw new \InvalidArgumentException('invalid value for $starting_daily_limit when calling MailPostDeliverabilityMailboxesByMailboxIdRequest., must be bigger than 0.');
        }

        $this->container['starting_daily_limit'] = $starting_daily_limit;

        return $this;
    }

    /**
     * Gets target_daily_limit
     *
     * @return int
     */
    public function getTargetDailyLimit()
    {
        return $this->container['target_daily_limit'];
    }

    /**
     * Sets target_daily_limit
     *
     * @param int $target_daily_limit target_daily_limit
     *
     * @return self
     */
    public function setTargetDailyLimit($target_daily_limit)
    {
        if (is_null($target_daily_limit)) {
            throw new \InvalidArgumentException('non-nullable target_daily_limit cannot be null');
        }
        if (($target_daily_limit > 100000)) {
            throw new \InvalidArgumentException('invalid value for $target_daily_limit when calling MailPostDeliverabilityMailboxesByMailboxIdRequest., must be smaller than or equal to 100000.');
        }
        if (($target_daily_limit <= 0)) {
            throw new \InvalidArgumentException('invalid value for $target_daily_limit when calling MailPostDeliverabilityMailboxesByMailboxIdRequest., must be bigger than 0.');
        }

        $this->container['target_daily_limit'] = $target_daily_limit;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


