<?php
/**
 * MailPostWebhooksRequest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Reacon\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Reacon\Sdk\Model;

use \ArrayAccess;
use \Reacon\Sdk\ObjectSerializer;

/**
 * MailPostWebhooksRequest Class Doc Comment
 *
 * @category Class
 * @package  Reacon\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class MailPostWebhooksRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'MailPostWebhooksRequest';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'endpoint' => 'string',
        'event_types' => 'string[]'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'endpoint' => 'uri',
        'event_types' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'endpoint' => false,
        'event_types' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'endpoint' => 'endpoint',
        'event_types' => 'eventTypes'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'endpoint' => 'setEndpoint',
        'event_types' => 'setEventTypes'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'endpoint' => 'getEndpoint',
        'event_types' => 'getEventTypes'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const EVENT_TYPES_MESSAGE_QUEUED = 'message.queued';
    public const EVENT_TYPES_MESSAGE_SUPPRESSED = 'message.suppressed';
    public const EVENT_TYPES_MESSAGE_SENDING = 'message.sending';
    public const EVENT_TYPES_MESSAGE_PROVIDER_ACCEPTED = 'message.provider_accepted';
    public const EVENT_TYPES_MESSAGE_DELIVERED = 'message.delivered';
    public const EVENT_TYPES_MESSAGE_DELIVERY_DEFERRED = 'message.delivery_deferred';
    public const EVENT_TYPES_MESSAGE_RETRY_SCHEDULED = 'message.retry_scheduled';
    public const EVENT_TYPES_MESSAGE_POLICY_DEFERRED = 'message.policy_deferred';
    public const EVENT_TYPES_MESSAGE_FAILED = 'message.failed';
    public const EVENT_TYPES_MESSAGE_CANCELLED = 'message.cancelled';
    public const EVENT_TYPES_MESSAGE_REPLIED = 'message.replied';
    public const EVENT_TYPES_MESSAGE_AUTO_REPLIED = 'message.auto_replied';
    public const EVENT_TYPES_MESSAGE_BOUNCED = 'message.bounced';
    public const EVENT_TYPES_MESSAGE_UNSUBSCRIBED = 'message.unsubscribed';
    public const EVENT_TYPES_MESSAGE_COMPLAINED = 'message.complained';
    public const EVENT_TYPES_MESSAGE_OPENED = 'message.opened';
    public const EVENT_TYPES_MESSAGE_CLICKED = 'message.clicked';
    public const EVENT_TYPES_MESSAGE_ENGAGEMENT_OBSERVED = 'message.engagement_observed';
    public const EVENT_TYPES_SIGNATURE_EXTRACTED = 'signature.extracted';
    public const EVENT_TYPES_SEQUENCE_STARTED = 'sequence.started';
    public const EVENT_TYPES_SEQUENCE_PAUSED = 'sequence.paused';
    public const EVENT_TYPES_SEQUENCE_RESUMED = 'sequence.resumed';
    public const EVENT_TYPES_SEQUENCE_CANCELLED = 'sequence.cancelled';
    public const EVENT_TYPES_SEQUENCE_COMPLETED = 'sequence.completed';
    public const EVENT_TYPES_CAMPAIGN_STARTED = 'campaign.started';
    public const EVENT_TYPES_CAMPAIGN_PAUSED = 'campaign.paused';
    public const EVENT_TYPES_CAMPAIGN_RESUMED = 'campaign.resumed';
    public const EVENT_TYPES_CAMPAIGN_CANCELLED = 'campaign.cancelled';
    public const EVENT_TYPES_CAMPAIGN_COMPLETED = 'campaign.completed';
    public const EVENT_TYPES_CONTACT_CREATED = 'contact.created';
    public const EVENT_TYPES_CONTACT_UPDATED = 'contact.updated';
    public const EVENT_TYPES_CONTACT_DELETED = 'contact.deleted';
    public const EVENT_TYPES_CONTACT_STAGE_CHANGED = 'contact.stage_changed';
    public const EVENT_TYPES_CONTACT_NOTE_ADDED = 'contact.note_added';
    public const EVENT_TYPES_TASK_CREATED = 'task.created';
    public const EVENT_TYPES_TASK_COMPLETED = 'task.completed';
    public const EVENT_TYPES_REPLY_CLASSIFIED = 'reply.classified';
    public const EVENT_TYPES_EXPERIMENT_ASSIGNED = 'experiment.assigned';
    public const EVENT_TYPES_EXPERIMENT_EXPOSED = 'experiment.exposed';
    public const EVENT_TYPES_EXPERIMENT_DECIDED = 'experiment.decided';
    public const EVENT_TYPES_EXPERIMENT_PAUSED = 'experiment.paused';
    public const EVENT_TYPES_EXPERIMENT_RESUMED = 'experiment.resumed';
    public const EVENT_TYPES_EXPERIMENT_ARCHIVED = 'experiment.archived';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getEventTypesAllowableValues()
    {
        return [
            self::EVENT_TYPES_MESSAGE_QUEUED,
            self::EVENT_TYPES_MESSAGE_SUPPRESSED,
            self::EVENT_TYPES_MESSAGE_SENDING,
            self::EVENT_TYPES_MESSAGE_PROVIDER_ACCEPTED,
            self::EVENT_TYPES_MESSAGE_DELIVERED,
            self::EVENT_TYPES_MESSAGE_DELIVERY_DEFERRED,
            self::EVENT_TYPES_MESSAGE_RETRY_SCHEDULED,
            self::EVENT_TYPES_MESSAGE_POLICY_DEFERRED,
            self::EVENT_TYPES_MESSAGE_FAILED,
            self::EVENT_TYPES_MESSAGE_CANCELLED,
            self::EVENT_TYPES_MESSAGE_REPLIED,
            self::EVENT_TYPES_MESSAGE_AUTO_REPLIED,
            self::EVENT_TYPES_MESSAGE_BOUNCED,
            self::EVENT_TYPES_MESSAGE_UNSUBSCRIBED,
            self::EVENT_TYPES_MESSAGE_COMPLAINED,
            self::EVENT_TYPES_MESSAGE_OPENED,
            self::EVENT_TYPES_MESSAGE_CLICKED,
            self::EVENT_TYPES_MESSAGE_ENGAGEMENT_OBSERVED,
            self::EVENT_TYPES_SIGNATURE_EXTRACTED,
            self::EVENT_TYPES_SEQUENCE_STARTED,
            self::EVENT_TYPES_SEQUENCE_PAUSED,
            self::EVENT_TYPES_SEQUENCE_RESUMED,
            self::EVENT_TYPES_SEQUENCE_CANCELLED,
            self::EVENT_TYPES_SEQUENCE_COMPLETED,
            self::EVENT_TYPES_CAMPAIGN_STARTED,
            self::EVENT_TYPES_CAMPAIGN_PAUSED,
            self::EVENT_TYPES_CAMPAIGN_RESUMED,
            self::EVENT_TYPES_CAMPAIGN_CANCELLED,
            self::EVENT_TYPES_CAMPAIGN_COMPLETED,
            self::EVENT_TYPES_CONTACT_CREATED,
            self::EVENT_TYPES_CONTACT_UPDATED,
            self::EVENT_TYPES_CONTACT_DELETED,
            self::EVENT_TYPES_CONTACT_STAGE_CHANGED,
            self::EVENT_TYPES_CONTACT_NOTE_ADDED,
            self::EVENT_TYPES_TASK_CREATED,
            self::EVENT_TYPES_TASK_COMPLETED,
            self::EVENT_TYPES_REPLY_CLASSIFIED,
            self::EVENT_TYPES_EXPERIMENT_ASSIGNED,
            self::EVENT_TYPES_EXPERIMENT_EXPOSED,
            self::EVENT_TYPES_EXPERIMENT_DECIDED,
            self::EVENT_TYPES_EXPERIMENT_PAUSED,
            self::EVENT_TYPES_EXPERIMENT_RESUMED,
            self::EVENT_TYPES_EXPERIMENT_ARCHIVED,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('endpoint', $data ?? [], null);
        $this->setIfExists('event_types', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['endpoint'] === null) {
            $invalidProperties[] = "'endpoint' can't be null";
        }
        if ((mb_strlen($this->container['endpoint']) > 2048)) {
            $invalidProperties[] = "invalid value for 'endpoint', the character length must be smaller than or equal to 2048.";
        }

        if (!is_null($this->container['event_types']) && (count($this->container['event_types']) > 64)) {
            $invalidProperties[] = "invalid value for 'event_types', number of items must be less than or equal to 64.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets endpoint
     *
     * @return string
     */
    public function getEndpoint()
    {
        return $this->container['endpoint'];
    }

    /**
     * Sets endpoint
     *
     * @param string $endpoint endpoint
     *
     * @return self
     */
    public function setEndpoint($endpoint)
    {
        if (is_null($endpoint)) {
            throw new \InvalidArgumentException('non-nullable endpoint cannot be null');
        }
        if ((mb_strlen($endpoint) > 2048)) {
            throw new \InvalidArgumentException('invalid length for $endpoint when calling MailPostWebhooksRequest., must be smaller than or equal to 2048.');
        }

        $this->container['endpoint'] = $endpoint;

        return $this;
    }

    /**
     * Gets event_types
     *
     * @return string[]|null
     */
    public function getEventTypes()
    {
        return $this->container['event_types'];
    }

    /**
     * Sets event_types
     *
     * @param string[]|null $event_types event_types
     *
     * @return self
     */
    public function setEventTypes($event_types)
    {
        if (is_null($event_types)) {
            throw new \InvalidArgumentException('non-nullable event_types cannot be null');
        }
        $allowedValues = $this->getEventTypesAllowableValues();
        if (array_diff($event_types, $allowedValues)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'event_types', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        if ((count($event_types) > 64)) {
            throw new \InvalidArgumentException('invalid value for $event_types when calling MailPostWebhooksRequest., number of items must be less than or equal to 64.');
        }
        $this->container['event_types'] = $event_types;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


