<?php
/**
 * PersonInsight
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Reacon\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Reacon\Sdk\Model;

use \ArrayAccess;
use \Reacon\Sdk\ObjectSerializer;

/**
 * PersonInsight Class Doc Comment
 *
 * @category Class
 * @package  Reacon\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PersonInsight implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'PersonInsight';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'aka' => 'string[]',
        'attributes' => '\Reacon\Sdk\Model\InsightAttribute[]',
        'company' => 'string',
        'created_at' => 'string',
        'emails' => 'string[]',
        'evidence' => '\Reacon\Sdk\Model\InsightEvidence[]',
        'first_name' => 'string',
        'identifiers' => '\Reacon\Sdk\Model\InsightIdentifier[]',
        'insights' => 'string[]',
        'job_position' => 'string',
        'last_name' => 'string',
        'offices' => '\Reacon\Sdk\Model\InsightOffice[]',
        'organization' => '\Reacon\Sdk\Model\InsightOrganization',
        'personal_address' => '\Reacon\Sdk\Model\InsightAddress',
        'phones' => '\Reacon\Sdk\Model\InsightPhone[]',
        'roles' => '\Reacon\Sdk\Model\InsightRole[]',
        'social_profiles' => '\Reacon\Sdk\Model\InsightSocialProfile[]',
        'sources' => '\Reacon\Sdk\Model\InsightSource[]',
        'summary' => 'string',
        'updated_at' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'aka' => null,
        'attributes' => null,
        'company' => null,
        'created_at' => null,
        'emails' => null,
        'evidence' => null,
        'first_name' => null,
        'identifiers' => null,
        'insights' => null,
        'job_position' => null,
        'last_name' => null,
        'offices' => null,
        'organization' => null,
        'personal_address' => null,
        'phones' => null,
        'roles' => null,
        'social_profiles' => null,
        'sources' => null,
        'summary' => null,
        'updated_at' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'aka' => false,
        'attributes' => false,
        'company' => false,
        'created_at' => false,
        'emails' => false,
        'evidence' => false,
        'first_name' => false,
        'identifiers' => false,
        'insights' => false,
        'job_position' => false,
        'last_name' => false,
        'offices' => false,
        'organization' => false,
        'personal_address' => false,
        'phones' => false,
        'roles' => false,
        'social_profiles' => false,
        'sources' => false,
        'summary' => false,
        'updated_at' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'aka' => 'aka',
        'attributes' => 'attributes',
        'company' => 'company',
        'created_at' => 'createdAt',
        'emails' => 'emails',
        'evidence' => 'evidence',
        'first_name' => 'firstName',
        'identifiers' => 'identifiers',
        'insights' => 'insights',
        'job_position' => 'jobPosition',
        'last_name' => 'lastName',
        'offices' => 'offices',
        'organization' => 'organization',
        'personal_address' => 'personalAddress',
        'phones' => 'phones',
        'roles' => 'roles',
        'social_profiles' => 'socialProfiles',
        'sources' => 'sources',
        'summary' => 'summary',
        'updated_at' => 'updatedAt'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'aka' => 'setAka',
        'attributes' => 'setAttributes',
        'company' => 'setCompany',
        'created_at' => 'setCreatedAt',
        'emails' => 'setEmails',
        'evidence' => 'setEvidence',
        'first_name' => 'setFirstName',
        'identifiers' => 'setIdentifiers',
        'insights' => 'setInsights',
        'job_position' => 'setJobPosition',
        'last_name' => 'setLastName',
        'offices' => 'setOffices',
        'organization' => 'setOrganization',
        'personal_address' => 'setPersonalAddress',
        'phones' => 'setPhones',
        'roles' => 'setRoles',
        'social_profiles' => 'setSocialProfiles',
        'sources' => 'setSources',
        'summary' => 'setSummary',
        'updated_at' => 'setUpdatedAt'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'aka' => 'getAka',
        'attributes' => 'getAttributes',
        'company' => 'getCompany',
        'created_at' => 'getCreatedAt',
        'emails' => 'getEmails',
        'evidence' => 'getEvidence',
        'first_name' => 'getFirstName',
        'identifiers' => 'getIdentifiers',
        'insights' => 'getInsights',
        'job_position' => 'getJobPosition',
        'last_name' => 'getLastName',
        'offices' => 'getOffices',
        'organization' => 'getOrganization',
        'personal_address' => 'getPersonalAddress',
        'phones' => 'getPhones',
        'roles' => 'getRoles',
        'social_profiles' => 'getSocialProfiles',
        'sources' => 'getSources',
        'summary' => 'getSummary',
        'updated_at' => 'getUpdatedAt'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('aka', $data ?? [], null);
        $this->setIfExists('attributes', $data ?? [], null);
        $this->setIfExists('company', $data ?? [], null);
        $this->setIfExists('created_at', $data ?? [], null);
        $this->setIfExists('emails', $data ?? [], null);
        $this->setIfExists('evidence', $data ?? [], null);
        $this->setIfExists('first_name', $data ?? [], null);
        $this->setIfExists('identifiers', $data ?? [], null);
        $this->setIfExists('insights', $data ?? [], null);
        $this->setIfExists('job_position', $data ?? [], null);
        $this->setIfExists('last_name', $data ?? [], null);
        $this->setIfExists('offices', $data ?? [], null);
        $this->setIfExists('organization', $data ?? [], null);
        $this->setIfExists('personal_address', $data ?? [], null);
        $this->setIfExists('phones', $data ?? [], null);
        $this->setIfExists('roles', $data ?? [], null);
        $this->setIfExists('social_profiles', $data ?? [], null);
        $this->setIfExists('sources', $data ?? [], null);
        $this->setIfExists('summary', $data ?? [], null);
        $this->setIfExists('updated_at', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['insights'] === null) {
            $invalidProperties[] = "'insights' can't be null";
        }
        if ($this->container['summary'] === null) {
            $invalidProperties[] = "'summary' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets aka
     *
     * @return string[]|null
     */
    public function getAka()
    {
        return $this->container['aka'];
    }

    /**
     * Sets aka
     *
     * @param string[]|null $aka aka
     *
     * @return self
     */
    public function setAka($aka)
    {
        if (is_null($aka)) {
            throw new \InvalidArgumentException('non-nullable aka cannot be null');
        }
        $this->container['aka'] = $aka;

        return $this;
    }

    /**
     * Gets attributes
     *
     * @return \Reacon\Sdk\Model\InsightAttribute[]|null
     */
    public function getAttributes()
    {
        return $this->container['attributes'];
    }

    /**
     * Sets attributes
     *
     * @param \Reacon\Sdk\Model\InsightAttribute[]|null $attributes attributes
     *
     * @return self
     */
    public function setAttributes($attributes)
    {
        if (is_null($attributes)) {
            throw new \InvalidArgumentException('non-nullable attributes cannot be null');
        }
        $this->container['attributes'] = $attributes;

        return $this;
    }

    /**
     * Gets company
     *
     * @return string|null
     */
    public function getCompany()
    {
        return $this->container['company'];
    }

    /**
     * Sets company
     *
     * @param string|null $company company
     *
     * @return self
     */
    public function setCompany($company)
    {
        if (is_null($company)) {
            throw new \InvalidArgumentException('non-nullable company cannot be null');
        }
        $this->container['company'] = $company;

        return $this;
    }

    /**
     * Gets created_at
     *
     * @return string|null
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     *
     * @param string|null $created_at created_at
     *
     * @return self
     */
    public function setCreatedAt($created_at)
    {
        if (is_null($created_at)) {
            throw new \InvalidArgumentException('non-nullable created_at cannot be null');
        }
        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets emails
     *
     * @return string[]|null
     */
    public function getEmails()
    {
        return $this->container['emails'];
    }

    /**
     * Sets emails
     *
     * @param string[]|null $emails emails
     *
     * @return self
     */
    public function setEmails($emails)
    {
        if (is_null($emails)) {
            throw new \InvalidArgumentException('non-nullable emails cannot be null');
        }
        $this->container['emails'] = $emails;

        return $this;
    }

    /**
     * Gets evidence
     *
     * @return \Reacon\Sdk\Model\InsightEvidence[]|null
     */
    public function getEvidence()
    {
        return $this->container['evidence'];
    }

    /**
     * Sets evidence
     *
     * @param \Reacon\Sdk\Model\InsightEvidence[]|null $evidence evidence
     *
     * @return self
     */
    public function setEvidence($evidence)
    {
        if (is_null($evidence)) {
            throw new \InvalidArgumentException('non-nullable evidence cannot be null');
        }
        $this->container['evidence'] = $evidence;

        return $this;
    }

    /**
     * Gets first_name
     *
     * @return string|null
     */
    public function getFirstName()
    {
        return $this->container['first_name'];
    }

    /**
     * Sets first_name
     *
     * @param string|null $first_name first_name
     *
     * @return self
     */
    public function setFirstName($first_name)
    {
        if (is_null($first_name)) {
            throw new \InvalidArgumentException('non-nullable first_name cannot be null');
        }
        $this->container['first_name'] = $first_name;

        return $this;
    }

    /**
     * Gets identifiers
     *
     * @return \Reacon\Sdk\Model\InsightIdentifier[]|null
     */
    public function getIdentifiers()
    {
        return $this->container['identifiers'];
    }

    /**
     * Sets identifiers
     *
     * @param \Reacon\Sdk\Model\InsightIdentifier[]|null $identifiers identifiers
     *
     * @return self
     */
    public function setIdentifiers($identifiers)
    {
        if (is_null($identifiers)) {
            throw new \InvalidArgumentException('non-nullable identifiers cannot be null');
        }
        $this->container['identifiers'] = $identifiers;

        return $this;
    }

    /**
     * Gets insights
     *
     * @return string[]
     */
    public function getInsights()
    {
        return $this->container['insights'];
    }

    /**
     * Sets insights
     *
     * @param string[] $insights insights
     *
     * @return self
     */
    public function setInsights($insights)
    {
        if (is_null($insights)) {
            throw new \InvalidArgumentException('non-nullable insights cannot be null');
        }
        $this->container['insights'] = $insights;

        return $this;
    }

    /**
     * Gets job_position
     *
     * @return string|null
     */
    public function getJobPosition()
    {
        return $this->container['job_position'];
    }

    /**
     * Sets job_position
     *
     * @param string|null $job_position job_position
     *
     * @return self
     */
    public function setJobPosition($job_position)
    {
        if (is_null($job_position)) {
            throw new \InvalidArgumentException('non-nullable job_position cannot be null');
        }
        $this->container['job_position'] = $job_position;

        return $this;
    }

    /**
     * Gets last_name
     *
     * @return string|null
     */
    public function getLastName()
    {
        return $this->container['last_name'];
    }

    /**
     * Sets last_name
     *
     * @param string|null $last_name last_name
     *
     * @return self
     */
    public function setLastName($last_name)
    {
        if (is_null($last_name)) {
            throw new \InvalidArgumentException('non-nullable last_name cannot be null');
        }
        $this->container['last_name'] = $last_name;

        return $this;
    }

    /**
     * Gets offices
     *
     * @return \Reacon\Sdk\Model\InsightOffice[]|null
     */
    public function getOffices()
    {
        return $this->container['offices'];
    }

    /**
     * Sets offices
     *
     * @param \Reacon\Sdk\Model\InsightOffice[]|null $offices offices
     *
     * @return self
     */
    public function setOffices($offices)
    {
        if (is_null($offices)) {
            throw new \InvalidArgumentException('non-nullable offices cannot be null');
        }
        $this->container['offices'] = $offices;

        return $this;
    }

    /**
     * Gets organization
     *
     * @return \Reacon\Sdk\Model\InsightOrganization|null
     */
    public function getOrganization()
    {
        return $this->container['organization'];
    }

    /**
     * Sets organization
     *
     * @param \Reacon\Sdk\Model\InsightOrganization|null $organization organization
     *
     * @return self
     */
    public function setOrganization($organization)
    {
        if (is_null($organization)) {
            throw new \InvalidArgumentException('non-nullable organization cannot be null');
        }
        $this->container['organization'] = $organization;

        return $this;
    }

    /**
     * Gets personal_address
     *
     * @return \Reacon\Sdk\Model\InsightAddress|null
     */
    public function getPersonalAddress()
    {
        return $this->container['personal_address'];
    }

    /**
     * Sets personal_address
     *
     * @param \Reacon\Sdk\Model\InsightAddress|null $personal_address personal_address
     *
     * @return self
     */
    public function setPersonalAddress($personal_address)
    {
        if (is_null($personal_address)) {
            throw new \InvalidArgumentException('non-nullable personal_address cannot be null');
        }
        $this->container['personal_address'] = $personal_address;

        return $this;
    }

    /**
     * Gets phones
     *
     * @return \Reacon\Sdk\Model\InsightPhone[]|null
     */
    public function getPhones()
    {
        return $this->container['phones'];
    }

    /**
     * Sets phones
     *
     * @param \Reacon\Sdk\Model\InsightPhone[]|null $phones phones
     *
     * @return self
     */
    public function setPhones($phones)
    {
        if (is_null($phones)) {
            throw new \InvalidArgumentException('non-nullable phones cannot be null');
        }
        $this->container['phones'] = $phones;

        return $this;
    }

    /**
     * Gets roles
     *
     * @return \Reacon\Sdk\Model\InsightRole[]|null
     */
    public function getRoles()
    {
        return $this->container['roles'];
    }

    /**
     * Sets roles
     *
     * @param \Reacon\Sdk\Model\InsightRole[]|null $roles roles
     *
     * @return self
     */
    public function setRoles($roles)
    {
        if (is_null($roles)) {
            throw new \InvalidArgumentException('non-nullable roles cannot be null');
        }
        $this->container['roles'] = $roles;

        return $this;
    }

    /**
     * Gets social_profiles
     *
     * @return \Reacon\Sdk\Model\InsightSocialProfile[]|null
     */
    public function getSocialProfiles()
    {
        return $this->container['social_profiles'];
    }

    /**
     * Sets social_profiles
     *
     * @param \Reacon\Sdk\Model\InsightSocialProfile[]|null $social_profiles social_profiles
     *
     * @return self
     */
    public function setSocialProfiles($social_profiles)
    {
        if (is_null($social_profiles)) {
            throw new \InvalidArgumentException('non-nullable social_profiles cannot be null');
        }
        $this->container['social_profiles'] = $social_profiles;

        return $this;
    }

    /**
     * Gets sources
     *
     * @return \Reacon\Sdk\Model\InsightSource[]|null
     */
    public function getSources()
    {
        return $this->container['sources'];
    }

    /**
     * Sets sources
     *
     * @param \Reacon\Sdk\Model\InsightSource[]|null $sources sources
     *
     * @return self
     */
    public function setSources($sources)
    {
        if (is_null($sources)) {
            throw new \InvalidArgumentException('non-nullable sources cannot be null');
        }
        $this->container['sources'] = $sources;

        return $this;
    }

    /**
     * Gets summary
     *
     * @return string
     */
    public function getSummary()
    {
        return $this->container['summary'];
    }

    /**
     * Sets summary
     *
     * @param string $summary summary
     *
     * @return self
     */
    public function setSummary($summary)
    {
        if (is_null($summary)) {
            throw new \InvalidArgumentException('non-nullable summary cannot be null');
        }
        $this->container['summary'] = $summary;

        return $this;
    }

    /**
     * Gets updated_at
     *
     * @return string|null
     */
    public function getUpdatedAt()
    {
        return $this->container['updated_at'];
    }

    /**
     * Sets updated_at
     *
     * @param string|null $updated_at updated_at
     *
     * @return self
     */
    public function setUpdatedAt($updated_at)
    {
        if (is_null($updated_at)) {
            throw new \InvalidArgumentException('non-nullable updated_at cannot be null');
        }
        $this->container['updated_at'] = $updated_at;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


